policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle Updatecli Policy Updates
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.9.1@sha256:5bbca67a9e31bf5432d5cae1452b9fc770014151ddd856f367ccb9ba46f6f8bb
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/updatecli-compose.yaml
  - name: Rust
    policy: ghcr.io/updatecli/policies/autodiscovery/cargo:0.7.1@sha256:5df42401067e344e85eef4a63d9f03e80099709f7832d49562164bec1fac1a2e
    values:
      - updatecli/values.d/scm.yaml
  - name: Github Actions autodiscovery
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.2.1@sha256:cfddec11464cc09615135f0f1e069f00ad24d28edc7cc6a4e8224e04c3699008
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubactions.yaml
