policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle Updatecli Policy Updates
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.9.0@sha256:2ae4e1ba471b996e58356a7b12ad8cf283b079ace8eac833d437d1e1ccb85bbb
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/updatecli-compose.yaml
  - name: Rust
    policy: ghcr.io/updatecli/policies/autodiscovery/cargo:0.7.0@sha256:82c57147cb70cadeec3c507d1aad0b86f40ce9ef4276f2f3f8cb0432131c55f9
    values:
      - updatecli/values.d/scm.yaml
  - name: Github Actions autodiscovery
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.1.0@sha256:ddac4fc192800a65e9a92669600db3eb66fe442610073d34202513b265ba7b29
    values:
      - updatecli/values.d/scm.yaml
