[unstable]
registry-auth = true
[registries.foresight-mining-software-corporation]
index = "ssh://git@ssh.shipyard.rs/foresight-mining-software-corporation/crate-index.git"
[net]
git-fetch-with-cli = true
#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "target-feature=+crt-static"]
