name: Test Build
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-linux:
    name: Test on Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@3b006c65b880ac90c7894f7d59b892008787cbec # v12
      - name: Build native package
        run: nix build .#default
      - name: Check binary
        run: |
          ls -lh result/bin/
          file result/bin/*
      - name: Test binary runs
        run: result/bin/cargo-fslabscli-x86_64-unknown-linux-musl --version
  test-macos:
    name: Test on macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@3b006c65b880ac90c7894f7d59b892008787cbec # v12
      - name: Build native package
        run: nix build .#default
      - name: Check binary
        run: |
          ls -lh result/bin/
          file result/bin/*
      - name: Test binary runs
        run: result/bin/cargo-fslabscli-aarch64-apple-darwin --version

